from collections.abc import Awaitable, Callable, Sequence
from typing import Any, Protocol, runtime_checkable

EventHandler = Callable[[str, dict[str, Any]], Awaitable[None]]


@runtime_checkable
class BrokerProvider(Protocol):
    async def probe(self) -> dict[str, Any]: ...

    async def place_order(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    async def cancel_order(self, broker_order_id: str, *, payload: dict[str, Any] | None = None) -> dict[str, Any]: ...

    async def authenticate(self, credentials: dict[str, Any]) -> dict[str, Any]: ...

    async def refresh_session(self, refresh_token: str | None) -> dict[str, Any]: ...

    async def list_capabilities(self) -> dict[str, Any]: ...

    async def fetch_whitelist_raw(self, *, format_hint: str | None = None) -> dict[str, Any]: ...


@runtime_checkable
class InfrastructureProvider(Protocol):
    async def probe(self) -> dict[str, Any]: ...

    async def create_ip(self, region: str, **kwargs: Any) -> dict[str, Any]: ...

    async def delete_ip(self, external_id: str) -> None: ...

    async def attach_ip(self, external_id: str, instance_external_id: str) -> None: ...

    async def detach_ip(self, external_id: str) -> None: ...

    async def create_instance(self, region: str, **kwargs: Any) -> dict[str, Any]: ...

    async def destroy_instance(self, external_id: str) -> None: ...

    async def suspend_instance(self, external_id: str) -> None: ...

    async def start_instance(self, external_id: str) -> None: ...

    async def set_auto_renew(self, resource_id: str, enabled: bool) -> None: ...

    async def list_ips(self, region: str | None = None) -> list[dict[str, Any]]: ...

    async def get_ip(self, external_id: str) -> dict[str, Any] | None: ...


@runtime_checkable
class CacheProvider(Protocol):
    async def get(self, key: str) -> str | None: ...

    async def set(self, key: str, value: str, ttl_seconds: int | None = None) -> None: ...


@runtime_checkable
class LockProvider(Protocol):
    async def acquire(self, key: str, ttl_seconds: float, token: str) -> bool: ...

    async def release(self, key: str, token: str) -> bool: ...


@runtime_checkable
class SessionProvider(Protocol):
    async def get(self, key: str) -> dict[str, Any] | None: ...

    async def set(self, key: str, value: dict[str, Any], ttl_seconds: int | None = None) -> None: ...

    async def delete(self, key: str) -> None: ...


@runtime_checkable
class EventProvider(Protocol):
    async def publish(self, topic: str, event: dict[str, Any]) -> None: ...

    async def subscribe(
        self,
        topics: Sequence[str],
        handler: EventHandler,
        *,
        consumer_group: str | None = None,
    ) -> None: ...

    async def run_consumer(self) -> None: ...

    async def probe(self) -> dict[str, Any]: ...

    async def aclose(self) -> None: ...


@runtime_checkable
class RateLimitProvider(Protocol):
    async def check(self, key: str, *, limit: float, window_seconds: float = 1.0) -> dict[str, Any]: ...

    async def consume(self, key: str, *, limit: float, window_seconds: float = 1.0) -> dict[str, Any]: ...
